# Generated by Django 5.1 on 2024-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="qr_img",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
