# Generated by Django 5.1 on 2024-08-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_rename_count_linkaudit_hits"),
        ("links", "0003_link_link_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_audit",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link",
                to="analytics.linkaudit",
            ),
        ),
    ]
