# Generated by Django 5.1 on 2024-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0005_alter_link_link_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="qr_img",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="qrs"
            ),
        ),
    ]
